README.md, examples/basic-attributer.html, examples/basic-grow-entering-edges-with-tooltip.html, examples/basic-grow-entering-edges.html, examples/basic-path-tween.html, examples/basic-shape-tween.html, examples/basic.html, examples/compare-edge-options.html, examples/demo-attributer.html, examples/demo-grow-entering-edges.html, examples/demo-path-tween.html, examples/demo-shape-tween.html, examples/demo.html, examples/zoom.html, package.json, src/dot.js, src/dotWorker.js, src/graphviz.js, src/logEvents.js, src/on.js, src/render.js, src/renderDot.js, src/transition.js, src/transitionFactory.js
=> Web worker

src/element.js, src/graphviz.js
=> Fix growing edges from shape tweened nodes

src/graphviz.js, src/zoom.js
Closes https://github.com/magjac/d3-graphviz/issues/16
=> Added resetZoom method

src/dot.js
Fixes https://github.com/magjac/d3-graphviz/issues/13
=> Handle growing edges to nodes with style "wedged"

src/render.js
Fixes https://github.com/magjac/d3-graphviz/issues/31
=> Bind callback to queued render call

src/zoom.js
Fixes https://github.com/magjac/d3-graphviz/issues/42
=> Fixed zoom when graph id is changed

src/render.js, test/render-remove-attribute-test.js
Fixes https://github.com/magjac/d3-graphviz/issues/49
=> Remove SVG element attribute when node attribute is removed

README.md, examples/basic-unkg.html, examples/demo.html, package.json, src/convertEqualSidedPolygons.js, src/dot.js, src/engine.js, src/fade.js, src/fit.js, src/graphviz.js, src/growEnteringEdges.js, src/height.js, src/keyMode.js, src/options.js, src/render.js, src/scale.js, src/selection/graphviz.js, src/totalMemory.js, src/tweenPaths.js, src/tweenPrecision.js, src/tweenShapes.js, src/width.js, src/zoom.js, test/dot-no-worker-test.js, test/dot-worker-through-text-javascript-tag-test.js, test/graphviz-options-test.js, test/graphviz-return-existing-renderer-test.js, test/transition-test.js, test/width-height-scale-fit-test.js, test/zoom-test.js
Added options, size, fit, scale and return of existing renderer instance
=> Improvements for Observable use

README.md, src/render.js, test/width-height-scale-fit-test.js
Fixes https://github.com/magjac/d3-graphviz/issues/69
=> When setting only SVG width, don't set height and vice versa

README.md, examples/basic-zoom-fit-window.html, src/graphviz.js, src/zoom.js, test/zoom-test.js
Closes https://github.com/magjac/d3-graphviz/issues/71
=> Added zoomScaleExtent method

src/render.js
Fixes https://github.com/magjac/d3-graphviz/issues/75
=> Corrected transform when rendering after pan or zoom

README.md, examples/demo-engines.html, src/engine.js, test/engine-test.js
Fixes https://github.com/magjac/d3-graphviz/issues/79
=> Don't throw error when layout engine is changed late

src/dot.js, test/dot-empty-node-id-test.js
Fixes https://github.com/magjac/d3-graphviz/issues/84
=> Fixed rendering of nodes with an empty string as node_id

src/drawNode.js
Fixes https://github.com/magjac/d3-graphviz/issues/89
=> Fixed Chrome problem when drawing node shape with polyline

src/render.js
Fixes https://github.com/magjac/d3-graphviz/issues/136.
=> Fix error when tween shapes but not fade

.github/workflows/node.js.yml, .travis.yml, README.md
Travis has stopped working and is no longer open source friendly.
=> Move CI to GitHub actions

.github/workflows/node.js.yml, package-lock.json, package.json, test/dot-data-test.js, test/graphviz-test.js, test/tooltip-test.js
Hello,
We use this lib at https://github.com/hedgedoc/react-client and can't update @hpcc-js/wasm because of this package. 
Therefore I've created this PR.
This PR does two things:
- Update @hpcc-js/wasm to 1.15.4
- Renews the lock file to update dependencies
Please merge it and publish a new release :)
=> Install updates

README.md, package-lock.json, package.json, src/dot.js, src/graphviz.js, src/workerCode.js, test/@hpcc-js/wasm/dist/graphvizlib.wasm, test/@hpcc-js/wasm/dist/wrapper.js, test/dot-no-worker-test.js, test/onerror-test.js
Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>
=> feat:  Bump @hpcc-js/wasm to v2.1.1

CHANGELOG.md, src/dot.js, test/simple-nodes-names-equal-to-property-of-javascript-object-type.js
Fixes https://github.com/magjac/d3-graphviz/issues/301.
=> Fix edge from a node with a name equal to a property of the JavaScript Object type

package-lock.json, package.json
Performed by:
npm upgrade @hpcc-js/wasm --save
=> Upgrade @hpcc-js/wasm to 2.16.0 (Graphviz 10.0.1)
